import { Rating } from './rating';

export interface Movie {
    actors: string,
    awards: string,
    box_office: string,
    country: string,
    dvd: string,
    director: string,
    genre: string,
    language: string,
    metascore: string,
    plot: string,
    poster: string,
    production: string,
    rated: string,
    ratings: Rating[],
    released: string,
    runtime: string,
    title: string,
    type: string,
    website: string,
    writer: string,
    year: string,
    imdb_id: string,
    imdb_rating: string,
    imdb_votes: string,
}
